{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ (printf "%s-webui" (include "ollama.fullname" .)) }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "ollama.selectorLabelsUI" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ollama.labels" . | nindent 8 }}
        {{- include "ollama.selectorLabelsUI" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: webui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              {{- if eq .Values.ui.type "open-webui" }}
              containerPort: 8080
              {{- else }}
              containerPort: 3210
              {{- end }}
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: OLLAMA_BASE_URL
              value: {{ (printf "http://%s" (include "ollama.fullname" .)) }}:{{ .Values.service.port }}
            - name: OLLAMA_PROXY_URL
              value: {{ (printf "http://%s" (include "ollama.fullname" .)) }}:{{ .Values.service.port }}
            {{- if eq .Values.ui.type "open-webui" }}
            - name: DATA_DIR
              value: "/app/backend/data"
            - name: OPENAI_API_KEY
              value: "0p3n-w3bu!"
            - name: OPENAI_API_BASE_URL
              value: {{ (printf "http://%s-pipelines:9099" (include "ollama.fullname" .)) }}
            {{- else }}
            - name: DATA_DIR
              value: "/data"
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: webui-data
              {{- if eq .Values.ui.type "open-webui" }}
              mountPath: /app/backend/data
              {{- else }}
              mountPath: /data
              {{- end }}
      volumes:
        - name: webui-data
          {{- if .Values.ui.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.ui.persistentVolume.claimName |  default (printf "%s-webui" (include "ollama.fullname" .)) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}